-- Model: file_manifest
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE OR REPLACE VIEW `dev_fd_bronze`.`ben_sales`.`file_manifest` AS
SELECT
    file_path,
    file_name,
    model_name,
    domain,
    file_format,
    row_count,
    file_size_bytes,
    checksum,
    ingested_at,
    status,
    named_struct(
        'schema_version', '3',
        'model', 'file_manifest',
        'sources', '',
        'git_commit', 'unknown',
        'deployed_at', '2026-03-24T11:11:25.816992+00:00',
        'compute_type', 'serverless',
        'contract_id', 'ben_sales.file_manifest',
        'version', 'v1',
        'columns', array(
        named_struct(
            'name', 'file_path',
            'expression', 'file_path',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'file_name',
            'expression', 'file_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'model_name',
            'expression', 'model_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'domain',
            'expression', 'domain',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'file_format',
            'expression', 'file_format',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'row_count',
            'expression', 'row_count',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'file_size_bytes',
            'expression', 'file_size_bytes',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'checksum',
            'expression', 'checksum',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'ingested_at',
            'expression', 'ingested_at',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'status',
            'expression', 'status',
            'op', 'PASSTHROUGH'
        )
    )
    ) AS _lineage
;

-- Execution summary
SELECT
    'file_manifest' AS model,
    'view' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_bronze`.`ben_sales`.`file_manifest`) AS rows_created,
    current_timestamp() AS completed_at;
