-- Model: stg_customers
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE OR REPLACE VIEW `public`.`silver`.`stg_customers` AS
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    cast(signup_date as date) as signup_date,
    country,
    cast(revenue as decimal(10,2)) as revenue,
    cast('{"schema_version": "3", "model": "stg_customers", "sources": "raw_customers", "git_commit": "unknown", "deployed_at": "2026-03-22T20:51:23.367834+00:00", "compute_type": "local", "contract_id": "silver.stg_customers", "version": "v1", "columns": [{"name": "customer_id", "expression": "customer_id", "op": "PASSTHROUGH"}, {"name": "first_name", "expression": "first_name", "op": "PASSTHROUGH"}, {"name": "last_name", "expression": "last_name", "op": "PASSTHROUGH"}, {"name": "email", "expression": "email", "op": "PASSTHROUGH"}, {"name": "signup_date", "expression": "cast(signup_date as date)", "op": "CAST"}, {"name": "country", "expression": "country", "op": "PASSTHROUGH"}, {"name": "revenue", "expression": "cast(revenue as decimal(10,2))", "op": "CAST"}]}' as varchar(8000)) AS _lineage
FROM `public`.`silver`.`raw_customers`
;
