-- ============================================
-- Lineage Graph + Log (auto-generated by forge)
-- ============================================

CREATE SCHEMA IF NOT EXISTS `dev_fd_meta`.`ben_sales`;

CREATE TABLE IF NOT EXISTS `dev_fd_meta`.`ben_sales`.lineage_graph (
    target_model    STRING     NOT NULL,
    source_model    STRING     NOT NULL,
    target_column   STRING,
    source_column   STRING,
    join_key        STRING,
    source_key      STRING,
    transform_type  STRING     NOT NULL,
    expression      STRING,
    target_catalog  STRING     NOT NULL,
    target_schema   STRING     NOT NULL,
    source_catalog  STRING     NOT NULL,
    source_schema   STRING     NOT NULL,
    git_commit      STRING     DEFAULT 'unknown',
    updated_at      TIMESTAMP  DEFAULT current_timestamp()
)
USING DELTA
TBLPROPERTIES('delta.feature.allowColumnDefaults' = 'supported');

CREATE TABLE IF NOT EXISTS `dev_fd_meta`.`ben_sales`.lineage_log (
    run_id          STRING     NOT NULL,
    model           STRING     NOT NULL,
    materialized    STRING,
    rows_created    BIGINT,
    catalog         STRING,
    schema          STRING,
    sources         STRING,
    git_commit      STRING,
    completed_at    TIMESTAMP  DEFAULT current_timestamp()
)
USING DELTA
TBLPROPERTIES('delta.feature.allowColumnDefaults' = 'supported');

TRUNCATE TABLE `dev_fd_meta`.`ben_sales`.lineage_graph;

INSERT INTO `dev_fd_meta`.`ben_sales`.lineage_graph (target_model, source_model, target_column, source_column, join_key, source_key, transform_type, expression, target_catalog, target_schema, source_catalog, source_schema) VALUES
  ('stg_customers', 'raw_customers', 'customer_id', 'customer_id', '', '', 'PASSTHROUGH', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_customers', 'raw_customers', 'first_name', 'first_name', '', '', 'PASSTHROUGH', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_customers', 'raw_customers', 'last_name', 'last_name', '', '', 'PASSTHROUGH', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_customers', 'raw_customers', 'email', 'email', '', '', 'PASSTHROUGH', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_customers', 'raw_customers', 'signup_date', 'signup_date', '', '', 'CAST', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_customers', 'raw_customers', 'country', 'country', '', '', 'PASSTHROUGH', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_customers', 'raw_customers', 'revenue', 'revenue', '', '', 'CAST', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_orders', 'raw_orders', 'order_id', 'order_id', '', '', 'PASSTHROUGH', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_orders', 'raw_orders', 'customer_id', 'customer_id', '', '', 'PASSTHROUGH', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_orders', 'raw_orders', 'product', 'product', '', '', 'PASSTHROUGH', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_orders', 'raw_orders', 'quantity', 'quantity', '', '', 'PASSTHROUGH', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_orders', 'raw_orders', 'unit_price', 'unit_price', '', '', 'CAST', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_orders', 'raw_orders', 'line_total', 'line_total', '', '', 'EXPRESSION', 'quantity * unit_price', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('stg_orders', 'raw_orders', 'order_date', 'order_date', '', '', 'CAST', '', 'dev_fd_bronze', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_clean', 'stg_customers', 'customer_id', 'customer_id', '', '', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_clean', 'stg_customers', 'first_name', 'first_name', '', '', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_clean', 'stg_customers', 'last_name', 'last_name', '', '', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_clean', 'stg_customers', 'email', 'email', '', '', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_clean', 'stg_customers', 'signup_date', 'signup_date', '', '', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_clean', 'stg_customers', 'country', 'country', '', '', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_clean', 'stg_customers', 'revenue', 'revenue', '', '', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_orders', 'customer_clean', 'customer_id', 'customer_id', 'customer_id', 'customer_id', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_orders', 'customer_clean', 'first_name', 'first_name', 'customer_id', 'customer_id', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_orders', 'customer_clean', 'last_name', 'last_name', 'customer_id', 'customer_id', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_orders', 'customer_clean', 'email', 'email', 'customer_id', 'customer_id', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_orders', 'customer_clean', 'country', 'country', 'customer_id', 'customer_id', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_orders', 'stg_orders', 'order_id', 'order_id', 'customer_id', 'customer_id', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_orders', 'stg_orders', 'product', 'product', 'customer_id', 'customer_id', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_orders', 'stg_orders', 'quantity', 'quantity', 'customer_id', 'customer_id', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_orders', 'stg_orders', 'unit_price', 'unit_price', 'customer_id', 'customer_id', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_orders', 'stg_orders', 'line_total', 'line_total', 'customer_id', 'customer_id', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_orders', 'stg_orders', 'order_date', 'order_date', 'customer_id', 'customer_id', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_bronze', 'ben_sales'),
  ('customer_summary', 'customer_orders', 'customer_id', 'customer_id', '', '', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_summary', 'customer_orders', 'first_name', 'first_name', '', '', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_summary', 'customer_orders', 'last_name', 'last_name', '', '', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_summary', 'customer_orders', 'email', 'email', '', '', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_summary', 'customer_orders', 'country', 'country', '', '', 'PASSTHROUGH', '', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_summary', 'customer_orders', 'total_orders', 'total_orders', '', '', 'AGGREGATION', 'count(order_id)', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_summary', 'customer_orders', 'total_revenue', 'total_revenue', '', '', 'AGGREGATION', 'sum(line_total)', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_summary', 'customer_orders', 'first_order_date', 'first_order_date', '', '', 'AGGREGATION', 'min(order_date)', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_summary', 'customer_orders', 'last_order_date', 'last_order_date', '', '', 'AGGREGATION', 'max(order_date)', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales'),
  ('customer_summary', 'customer_orders', 'tier', 'tier', '', '', 'UDF', 'loyalty_tier(total_revenue)', 'dev_fd_silver', 'ben_sales', 'dev_fd_silver', 'ben_sales');

