-- Model: stg_customers
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE OR REPLACE VIEW `dev_fd_silver`.`dev_myproject`.`stg_customers` AS
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    cast(signup_date as date) as signup_date,
    country,
    cast(revenue as decimal(10,2)) as revenue,
    named_struct(
        'schema_version', '3',
        'model', 'stg_customers',
        'sources', 'raw_customers',
        'git_commit', 'unknown',
        'deployed_at', '2026-03-22T22:06:32.907689+00:00',
        'compute_type', 'serverless',
        'contract_id', 'dev_myproject.stg_customers',
        'version', 'v1',
        'columns', array(
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'first_name',
            'expression', 'first_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'last_name',
            'expression', 'last_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'email',
            'expression', 'email',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'signup_date',
            'expression', 'cast(signup_date as date)',
            'op', 'CAST'
        ),
        named_struct(
            'name', 'country',
            'expression', 'country',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'revenue',
            'expression', 'cast(revenue as decimal(10,2))',
            'op', 'CAST'
        )
    )
    ) AS _lineage
FROM `dev_fd_silver`.`dev_myproject`.`raw_customers`
;
