-- Model: customer_clean
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE OR REPLACE TABLE `public`.`silver`.`customer_clean`
USING DELTA
AS
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    signup_date,
    country,
    revenue,
    cast('{"schema_version": "3", "model": "customer_clean", "sources": "stg_customers", "git_commit": "unknown", "deployed_at": "2026-03-22T20:51:23.367834+00:00", "compute_type": "local", "contract_id": "silver.customer_clean", "version": "v2", "columns": [{"name": "customer_id", "expression": "customer_id", "op": "PASSTHROUGH"}, {"name": "first_name", "expression": "first_name", "op": "PASSTHROUGH"}, {"name": "last_name", "expression": "last_name", "op": "PASSTHROUGH"}, {"name": "email", "expression": "email", "op": "PASSTHROUGH"}, {"name": "signup_date", "expression": "signup_date", "op": "PASSTHROUGH"}, {"name": "country", "expression": "country", "op": "PASSTHROUGH"}, {"name": "revenue", "expression": "revenue", "op": "PASSTHROUGH"}]}' as varchar(8000)) AS _lineage
FROM `public`.`silver`.`stg_customers`
;
