-- Quarantine tables
-- Generated by: forge compile --pure-sql
CREATE SCHEMA IF NOT EXISTS `dev_fd_meta`.`ben_sales`;

CREATE TABLE IF NOT EXISTS `dev_fd_meta`.`ben_sales`.`transform_quarantine` (
    model_name STRING NOT NULL,
    source_table STRING,
    quarantine_rule STRING NOT NULL,
    row_data STRING NOT NULL,
    git_commit STRING,
    detected_at TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `dev_fd_meta`.`ben_sales`.`ingest_quarantine` (
    file_path STRING NOT NULL,
    file_name STRING NOT NULL,
    target_model STRING,
    file_format STRING,
    file_size_bytes BIGINT,
    error_message STRING,
    git_commit STRING,
    detected_at TIMESTAMP
) USING DELTA;
