-- Model: raw_customers
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE OR REPLACE VIEW `dev_fd_bronze`.`ben_sales`.`raw_customers` AS
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    signup_date,
    country,
    revenue,
    named_struct(
        'schema_version', '3',
        'model', 'raw_customers',
        'sources', '',
        'git_commit', 'unknown',
        'deployed_at', '2026-03-24T10:52:11.334973+00:00',
        'compute_type', 'serverless',
        'contract_id', 'ben_sales.raw_customers',
        'version', 'v1',
        'columns', array(
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'first_name',
            'expression', 'first_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'last_name',
            'expression', 'last_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'email',
            'expression', 'email',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'signup_date',
            'expression', 'signup_date',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'country',
            'expression', 'country',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'revenue',
            'expression', 'revenue',
            'op', 'PASSTHROUGH'
        )
    )
    ) AS _lineage
;

-- Execution summary
SELECT
    'raw_customers' AS model,
    'view' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_bronze`.`ben_sales`.`raw_customers`) AS rows_created,
    current_timestamp() AS completed_at;
