-- Model: customer_clean
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE OR REPLACE TABLE `dev_fd_bronze`.`dev_myproject`.`customer_clean`
USING DELTA
AS
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    signup_date,
    country,
    revenue,
    named_struct(
        'schema_version', '3',
        'model', 'customer_clean',
        'sources', 'stg_customers',
        'git_commit', 'unknown',
        'deployed_at', '2026-03-22T22:06:32.907689+00:00',
        'compute_type', 'serverless',
        'contract_id', 'dev_myproject.customer_clean',
        'version', 'v2',
        'columns', array(
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'first_name',
            'expression', 'first_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'last_name',
            'expression', 'last_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'email',
            'expression', 'email',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'signup_date',
            'expression', 'signup_date',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'country',
            'expression', 'country',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'revenue',
            'expression', 'revenue',
            'op', 'PASSTHROUGH'
        )
    )
    ) AS _lineage
FROM `dev_fd_silver`.`dev_myproject`.`stg_customers`
;
