-- Model: stg_orders
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE OR REPLACE VIEW `dev_fd_silver`.`dev_demo`.`stg_orders` AS
SELECT
    order_id,
    customer_id,
    product,
    quantity,
    cast(unit_price as decimal(10,2)) as unit_price,
    quantity * unit_price as line_total,
    cast(order_date as date) as order_date,
    named_struct(
        'schema_version', '3',
        'model', 'stg_orders',
        'sources', 'raw_orders',
        'git_commit', 'unknown',
        'deployed_at', '2026-03-22T22:27:19.499838+00:00',
        'compute_type', 'serverless',
        'contract_id', 'dev_demo.stg_orders',
        'version', 'v1',
        'columns', array(
        named_struct(
            'name', 'order_id',
            'expression', 'order_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'product',
            'expression', 'product',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'quantity',
            'expression', 'quantity',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'unit_price',
            'expression', 'cast(unit_price as decimal(10,2))',
            'op', 'CAST'
        ),
        named_struct(
            'name', 'line_total',
            'expression', 'quantity * unit_price',
            'op', 'EXPRESSION'
        ),
        named_struct(
            'name', 'order_date',
            'expression', 'cast(order_date as date)',
            'op', 'CAST'
        )
    )
    ) AS _lineage
FROM `dev_fd_silver`.`dev_demo`.`raw_orders`
;
