-- Model: raw_orders
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE OR REPLACE VIEW `dev_fd_bronze`.`ben_sales`.`raw_orders` AS
SELECT
    order_id,
    customer_id,
    product,
    quantity,
    unit_price,
    order_date,
    named_struct(
        'schema_version', '3',
        'model', 'raw_orders',
        'sources', '',
        'git_commit', 'unknown',
        'deployed_at', '2026-03-24T11:32:14.219431+00:00',
        'compute_type', 'serverless',
        'contract_id', 'ben_sales.raw_orders',
        'version', 'v1',
        'columns', array(
        named_struct(
            'name', 'order_id',
            'expression', 'order_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'product',
            'expression', 'product',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'quantity',
            'expression', 'quantity',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'unit_price',
            'expression', 'unit_price',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'order_date',
            'expression', 'order_date',
            'op', 'PASSTHROUGH'
        )
    )
    ) AS _lineage
;

-- Execution summary
SELECT
    'raw_orders' AS model,
    'view' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_bronze`.`ben_sales`.`raw_orders`) AS rows_created,
    current_timestamp() AS completed_at;
