-- Model: raw_customers
-- Managed by: python
-- Schema created by forge; data populated by python task.
-- Generated by: forge compile --pure-sql

CREATE SCHEMA IF NOT EXISTS `dev_fd_bronze`.`ben_sales`;

CREATE TABLE IF NOT EXISTS `dev_fd_bronze`.`ben_sales`.`raw_customers` (
    customer_id INT,
    first_name STRING,
    last_name STRING,
    email STRING,
    signup_date DATE,
    country STRING,
    revenue DECIMAL(10,2)
)
USING DELTA;

-- Execution summary
SELECT
    'raw_customers' AS model,
    'managed_by_python' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_bronze`.`ben_sales`.`raw_customers`) AS rows_created,
    current_timestamp() AS completed_at;

-- Lineage log (run_id captured at runtime)
INSERT INTO `dev_fd_meta`.`ben_sales`.lineage_log
    (run_id, model, materialized, rows_created, catalog, schema, sources, git_commit, completed_at)
SELECT
    '{{job.run_id}}',
    'raw_customers',
    'managed_by_python',
    COUNT(*),
    'dev_fd_bronze',
    'ben_sales',
    '',
    'unknown',
    current_timestamp()
FROM `dev_fd_bronze`.`ben_sales`.`raw_customers`;
