-- Model: stg_orders
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE OR REPLACE VIEW `public`.`silver`.`stg_orders` AS
SELECT
    order_id,
    customer_id,
    product,
    quantity,
    cast(unit_price as decimal(10,2)) as unit_price,
    quantity * unit_price as line_total,
    cast(order_date as date) as order_date,
    cast('{"schema_version": "3", "model": "stg_orders", "sources": "raw_orders", "git_commit": "unknown", "deployed_at": "2026-03-22T20:51:23.367834+00:00", "compute_type": "local", "contract_id": "silver.stg_orders", "version": "v1", "columns": [{"name": "order_id", "expression": "order_id", "op": "PASSTHROUGH"}, {"name": "customer_id", "expression": "customer_id", "op": "PASSTHROUGH"}, {"name": "product", "expression": "product", "op": "PASSTHROUGH"}, {"name": "quantity", "expression": "quantity", "op": "PASSTHROUGH"}, {"name": "unit_price", "expression": "cast(unit_price as decimal(10,2))", "op": "CAST"}, {"name": "line_total", "expression": "quantity * unit_price", "op": "EXPRESSION"}, {"name": "order_date", "expression": "cast(order_date as date)", "op": "CAST"}]}' as varchar(8000)) AS _lineage
FROM `public`.`silver`.`raw_orders`
;
