-- Volumes
-- Generated by: forge compile --pure-sql

-- Volume: landing
-- Generated by: forge compile
CREATE VOLUME IF NOT EXISTS `dev_fd_bronze`.`ben_sales`.`landing`;
COMMENT ON VOLUME `dev_fd_bronze`.`ben_sales`.`landing` IS 'Landing zone for inbound data files';
