-- Model: raw_orders
-- Managed by: python
-- Schema created by forge; data populated by python task.
-- Generated by: forge compile --pure-sql

CREATE TABLE IF NOT EXISTS `dev_fd_bronze`.`ben_sales`.`raw_orders` (
    order_id INT,
    customer_id INT,
    product STRING,
    quantity INT,
    unit_price DECIMAL(10,2),
    order_date DATE
)
USING DELTA;

-- Execution summary
SELECT
    'raw_orders' AS model,
    'managed_by_python' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_bronze`.`ben_sales`.`raw_orders`) AS rows_created,
    current_timestamp() AS completed_at;

-- Lineage log (run_id captured at runtime)
INSERT INTO `dev_fd_meta`.`ben_sales`.lineage_log
    (run_id, model, materialized, rows_created, catalog, schema, sources, git_commit, completed_at)
VALUES (
    '{{job.run_id}}',
    'raw_orders',
    'managed_by_python',
    (SELECT COUNT(*) FROM `dev_fd_bronze`.`ben_sales`.`raw_orders`),
    'dev_fd_bronze',
    'ben_sales',
    '',
    'unknown',
    current_timestamp()
);
