-- Model: customer_orders
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE OR REPLACE TABLE `public`.`silver`.`customer_orders`
USING DELTA
AS
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.email,
    c.country,
    o.order_id,
    o.product,
    o.quantity,
    o.unit_price,
    o.line_total,
    o.order_date,
    cast('{"schema_version": "3", "model": "customer_orders", "sources": "customer_clean, stg_orders", "git_commit": "unknown", "deployed_at": "2026-03-22T20:51:23.367834+00:00", "compute_type": "local", "contract_id": "silver.customer_orders", "version": "v1", "columns": [{"name": "customer_id", "expression": "customer_id", "op": "PASSTHROUGH"}, {"name": "first_name", "expression": "first_name", "op": "PASSTHROUGH"}, {"name": "last_name", "expression": "last_name", "op": "PASSTHROUGH"}, {"name": "email", "expression": "email", "op": "PASSTHROUGH"}, {"name": "country", "expression": "country", "op": "PASSTHROUGH"}, {"name": "order_id", "expression": "order_id", "op": "PASSTHROUGH"}, {"name": "product", "expression": "product", "op": "PASSTHROUGH"}, {"name": "quantity", "expression": "quantity", "op": "PASSTHROUGH"}, {"name": "unit_price", "expression": "unit_price", "op": "PASSTHROUGH"}, {"name": "line_total", "expression": "line_total", "op": "PASSTHROUGH"}, {"name": "order_date", "expression": "order_date", "op": "PASSTHROUGH"}]}' as varchar(8000)) AS _lineage
FROM `public`.`silver`.`customer_clean` c
INNER JOIN `public`.`silver`.`stg_orders` o
    ON c.customer_id = o.customer_id
;
