-- Seed: ingestion_config
-- Source: dbt/seeds/ingestion_config.csv
-- Generated by: forge compile --pure-sql

CREATE SCHEMA IF NOT EXISTS `dev_fd_meta`.`ben_config`;

CREATE TABLE IF NOT EXISTS `dev_fd_meta`.`ben_config`.`ingestion_config` (
    config_id INT NOT NULL,
    ingest_type STRING NOT NULL,
    source_name STRING NOT NULL,
    target_model STRING NOT NULL,
    volume_name STRING,
    file_regex STRING,
    file_format STRING,
    has_header BOOLEAN,
    delimiter STRING,
    active BOOLEAN
) USING DELTA;

TRUNCATE TABLE `dev_fd_meta`.`ben_config`.`ingestion_config`;

INSERT INTO `dev_fd_meta`.`ben_config`.`ingestion_config` (config_id, ingest_type, source_name, target_model, volume_name, file_regex, file_format, has_header, delimiter, active) VALUES
  (1, 'volume', 'customer_feed', 'raw_customers', 'landing', '^raw_customers.*\.csv$', 'csv', true, ',', true),
  (2, 'volume', 'order_feed', 'raw_orders', 'landing', '^raw_orders.*\.csv$', 'csv', true, ',', true);

-- Execution summary
SELECT
    'ingestion_config' AS seed,
    (SELECT COUNT(*) FROM `dev_fd_meta`.`ben_config`.`ingestion_config`) AS rows_loaded,
    current_timestamp() AS completed_at;
