-- Model: customer_summary
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE OR REPLACE TABLE `public`.`silver`.`customer_summary`
USING DELTA
AS
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    country,
    count(order_id) as total_orders,
    sum(line_total) as total_revenue,
    min(order_date) as first_order_date,
    max(order_date) as last_order_date,
    loyalty_tier(total_revenue) as tier,
    cast('{"schema_version": "3", "model": "customer_summary", "sources": "customer_orders", "git_commit": "unknown", "deployed_at": "2026-03-22T20:51:23.367834+00:00", "compute_type": "local", "contract_id": "silver.customer_summary", "version": "v1", "columns": [{"name": "customer_id", "expression": "customer_id", "op": "PASSTHROUGH"}, {"name": "first_name", "expression": "first_name", "op": "PASSTHROUGH"}, {"name": "last_name", "expression": "last_name", "op": "PASSTHROUGH"}, {"name": "email", "expression": "email", "op": "PASSTHROUGH"}, {"name": "country", "expression": "country", "op": "PASSTHROUGH"}, {"name": "total_orders", "expression": "count(order_id)", "op": "AGGREGATION"}, {"name": "total_revenue", "expression": "sum(line_total)", "op": "AGGREGATION"}, {"name": "first_order_date", "expression": "min(order_date)", "op": "AGGREGATION"}, {"name": "last_order_date", "expression": "max(order_date)", "op": "AGGREGATION"}, {"name": "tier", "expression": "loyalty_tier(total_revenue)", "op": "UDF"}]}' as varchar(8000)) AS _lineage
FROM `public`.`silver`.`customer_orders`
GROUP BY
    customer_id, first_name, last_name, email, country
;
