-- Model: file_manifest
-- Managed by: python
-- Schema created by forge; data populated by python task.
-- Generated by: forge compile --pure-sql

CREATE SCHEMA IF NOT EXISTS `dev_fd_bronze`.`ben_sales`;

CREATE TABLE IF NOT EXISTS `dev_fd_bronze`.`ben_sales`.`file_manifest` (
    file_path STRING NOT NULL,
    file_name STRING NOT NULL,
    model_name STRING NOT NULL,
    domain STRING,
    file_format STRING,
    row_count INT,
    file_size_bytes INT,
    checksum STRING,
    ingested_at TIMESTAMP NOT NULL,
    status STRING,
    _origin_file STRING,
    _inserted_at TIMESTAMP
)
USING DELTA;

-- Execution summary
SELECT
    'file_manifest' AS model,
    'managed_by_python' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_bronze`.`ben_sales`.`file_manifest`) AS rows_created,
    current_timestamp() AS completed_at;

-- Lineage log (run_id captured at runtime)
INSERT INTO `dev_fd_meta`.`ben_sales`.lineage_log
    (run_id, model, materialized, rows_created, catalog, schema, sources, git_commit, completed_at)
SELECT
    :run_id,
    'file_manifest',
    'managed_by_python',
    COUNT(*),
    'dev_fd_bronze',
    'ben_sales',
    '',
    'unknown',
    current_timestamp()
FROM `dev_fd_bronze`.`ben_sales`.`file_manifest`;
