-- Model: customer_clean
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE SCHEMA IF NOT EXISTS `dev_fd_silver`.`ben_sales`;

CREATE OR REPLACE TABLE `dev_fd_silver`.`ben_sales`.`customer_clean`
USING DELTA
AS
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    signup_date,
    country,
    revenue,
    named_struct(
        'schema_version', '3',
        'model', 'customer_clean',
        'sources', 'stg_customers',
        'git_commit', 'unknown',
        'deployed_at', '2026-03-24T13:45:56.084939+00:00',
        'compute_type', 'serverless',
        'contract_id', 'ben_sales.customer_clean',
        'version', 'v2',
        'columns', array(
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'first_name',
            'expression', 'first_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'last_name',
            'expression', 'last_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'email',
            'expression', 'email',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'signup_date',
            'expression', 'signup_date',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'country',
            'expression', 'country',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'revenue',
            'expression', 'revenue',
            'op', 'PASSTHROUGH'
        )
    )
    ) AS _lineage
FROM `dev_fd_bronze`.`ben_sales`.`stg_customers`
;

-- Execution summary
SELECT
    'customer_clean' AS model,
    'table' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_silver`.`ben_sales`.`customer_clean`) AS rows_created,
    current_timestamp() AS completed_at;

-- Lineage log (run_id captured at runtime)
INSERT INTO `dev_fd_meta`.`ben_sales`.lineage_log
    (run_id, model, materialized, rows_created, catalog, schema, sources, git_commit, completed_at)
VALUES (
    '{{job.run_id}}',
    'customer_clean',
    'table',
    (SELECT COUNT(*) FROM `dev_fd_silver`.`ben_sales`.`customer_clean`),
    'dev_fd_silver',
    'ben_sales',
    'stg_customers',
    'unknown',
    current_timestamp()
);
