-- Model: stg_orders
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE SCHEMA IF NOT EXISTS `dev_fd_bronze`.`ben_sales`;

CREATE OR REPLACE VIEW `dev_fd_bronze`.`ben_sales`.`stg_orders` AS
SELECT
    order_id,
    customer_id,
    product,
    quantity,
    cast(unit_price as decimal(10,2)) as unit_price,
    quantity * unit_price as line_total,
    cast(order_date as date) as order_date,
    named_struct(
        'schema_version', '3',
        'model', 'stg_orders',
        'sources', 'raw_orders',
        'git_commit', 'unknown',
        'deployed_at', '2026-03-24T13:38:16.555435+00:00',
        'compute_type', 'serverless',
        'contract_id', 'ben_sales.stg_orders',
        'version', 'v1',
        'columns', array(
        named_struct(
            'name', 'order_id',
            'expression', 'order_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'product',
            'expression', 'product',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'quantity',
            'expression', 'quantity',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'unit_price',
            'expression', 'cast(unit_price as decimal(10,2))',
            'op', 'CAST'
        ),
        named_struct(
            'name', 'line_total',
            'expression', 'quantity * unit_price',
            'op', 'EXPRESSION'
        ),
        named_struct(
            'name', 'order_date',
            'expression', 'cast(order_date as date)',
            'op', 'CAST'
        )
    )
    ) AS _lineage
FROM `dev_fd_bronze`.`ben_sales`.`raw_orders`
;

-- Execution summary
SELECT
    'stg_orders' AS model,
    'view' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_bronze`.`ben_sales`.`stg_orders`) AS rows_created,
    current_timestamp() AS completed_at;

-- Lineage log (run_id captured at runtime)
INSERT INTO `dev_fd_meta`.`ben_sales`.lineage_log
    (run_id, model, materialized, rows_created, catalog, schema, sources, git_commit, completed_at)
VALUES (
    '{{job.run_id}}',
    'stg_orders',
    'view',
    (SELECT COUNT(*) FROM `dev_fd_bronze`.`ben_sales`.`stg_orders`),
    'dev_fd_bronze',
    'ben_sales',
    'raw_orders',
    'unknown',
    current_timestamp()
);
