-- Model: customer_orders
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE OR REPLACE TABLE `dev_fd_silver`.`ben_sales`.`customer_orders`
USING DELTA
AS
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.email,
    c.country,
    o.order_id,
    o.product,
    o.quantity,
    o.unit_price,
    o.line_total,
    o.order_date,
    named_struct(
        'schema_version', '3',
        'model', 'customer_orders',
        'sources', 'customer_clean, stg_orders',
        'git_commit', 'unknown',
        'deployed_at', '2026-03-24T10:52:11.334973+00:00',
        'compute_type', 'serverless',
        'contract_id', 'ben_sales.customer_orders',
        'version', 'v1',
        'columns', array(
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'first_name',
            'expression', 'first_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'last_name',
            'expression', 'last_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'email',
            'expression', 'email',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'country',
            'expression', 'country',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'order_id',
            'expression', 'order_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'product',
            'expression', 'product',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'quantity',
            'expression', 'quantity',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'unit_price',
            'expression', 'unit_price',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'line_total',
            'expression', 'line_total',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'order_date',
            'expression', 'order_date',
            'op', 'PASSTHROUGH'
        )
    )
    ) AS _lineage
FROM `dev_fd_silver`.`ben_sales`.`customer_clean` c
INNER JOIN `dev_fd_bronze`.`ben_sales`.`stg_orders` o
    ON c.customer_id = o.customer_id
;

-- Execution summary
SELECT
    'customer_orders' AS model,
    'table' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_silver`.`ben_sales`.`customer_orders`) AS rows_created,
    current_timestamp() AS completed_at;
