-- Model: raw_orders
-- Managed by: ingest_from_volume
-- Schema created by forge; data populated by ingest_from_volume task.
-- Generated by: forge compile --pure-sql

CREATE SCHEMA IF NOT EXISTS `dev_fd_bronze`.`ben_sales`;

CREATE TABLE IF NOT EXISTS `dev_fd_bronze`.`ben_sales`.`raw_orders` (
    order_id INT,
    customer_id INT,
    product STRING,
    quantity INT,
    unit_price DECIMAL(10,2),
    order_date DATE,
    _origin_file STRING,
    _inserted_at TIMESTAMP
)
USING DELTA;

-- Execution summary
SELECT
    'raw_orders' AS model,
    'managed_by_ingest_from_volume' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_bronze`.`ben_sales`.`raw_orders`) AS rows_created,
    current_timestamp() AS completed_at;

-- Lineage log (run_id captured at runtime)
INSERT INTO `dev_fd_meta`.`ben_lineage`.lineage_log
    (run_id, model, materialized, rows_created, catalog, schema, sources, git_commit, completed_at)
SELECT
    :run_id,
    'raw_orders',
    'managed_by_ingest_from_volume',
    COUNT(*),
    'dev_fd_bronze',
    'ben_sales',
    '',
    'unknown',
    current_timestamp()
FROM `dev_fd_bronze`.`ben_sales`.`raw_orders`;
