-- Model: stg_customers
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE SCHEMA IF NOT EXISTS `dev_fd_bronze`.`ben_sales`;

CREATE OR REPLACE VIEW `dev_fd_bronze`.`ben_sales`.`stg_customers` AS
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    cast(signup_date as date) as signup_date,
    country,
    cast(revenue as decimal(10,2)) as revenue,
    named_struct(
        'schema_version', '4',
        'model', 'stg_customers',
        'sources', 'raw_customers',
        'origin_files', coalesce(_lineage.origin_files, array(_origin_file)),
        'ingested_ats', coalesce(_lineage.ingested_ats, array(_inserted_at)),
        'upstream', to_json(_lineage),
        'git_commit', 'unknown',
        'deployed_at', '2026-03-24T20:44:44.215280+00:00',
        'compute_type', 'serverless',
        'contract_id', 'ben_sales.stg_customers',
        'version', 'v1',
        'columns', array(
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'first_name',
            'expression', 'first_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'last_name',
            'expression', 'last_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'email',
            'expression', 'email',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'signup_date',
            'expression', 'cast(signup_date as date)',
            'op', 'CAST'
        ),
        named_struct(
            'name', 'country',
            'expression', 'country',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'revenue',
            'expression', 'cast(revenue as decimal(10,2))',
            'op', 'CAST'
        )
    )
    ) AS _lineage
FROM `dev_fd_bronze`.`ben_sales`.`raw_customers`
;

-- Execution summary
SELECT
    'stg_customers' AS model,
    'view' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_bronze`.`ben_sales`.`stg_customers`) AS rows_created,
    current_timestamp() AS completed_at;

-- Lineage log (run_id captured at runtime)
INSERT INTO `dev_fd_meta`.`ben_sales`.lineage_log
    (run_id, model, materialized, rows_created, catalog, schema, sources, git_commit, completed_at)
SELECT
    :run_id,
    'stg_customers',
    'view',
    COUNT(*),
    'dev_fd_bronze',
    'ben_sales',
    'raw_customers',
    'unknown',
    current_timestamp()
FROM `dev_fd_bronze`.`ben_sales`.`stg_customers`;
