-- Model: customer_summary
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE SCHEMA IF NOT EXISTS `dev_fd_silver`.`ben_sales`;

CREATE OR REPLACE TABLE `dev_fd_silver`.`ben_sales`.`customer_summary`
USING DELTA
AS
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    country,
    count(order_id) as total_orders,
    sum(line_total) as total_revenue,
    min(order_date) as first_order_date,
    max(order_date) as last_order_date,
    `dev_fd_silver`.`ben_sales`.loyalty_tier(total_revenue) as tier,
    named_struct(
        'schema_version', '3',
        'model', 'customer_summary',
        'sources', 'customer_orders',
        'git_commit', 'unknown',
        'deployed_at', '2026-03-24T16:36:04.526701+00:00',
        'compute_type', 'serverless',
        'contract_id', 'ben_sales.customer_summary',
        'version', 'v1',
        'columns', array(
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'first_name',
            'expression', 'first_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'last_name',
            'expression', 'last_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'email',
            'expression', 'email',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'country',
            'expression', 'country',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'total_orders',
            'expression', 'count(order_id)',
            'op', 'AGGREGATION'
        ),
        named_struct(
            'name', 'total_revenue',
            'expression', 'sum(line_total)',
            'op', 'AGGREGATION'
        ),
        named_struct(
            'name', 'first_order_date',
            'expression', 'min(order_date)',
            'op', 'AGGREGATION'
        ),
        named_struct(
            'name', 'last_order_date',
            'expression', 'max(order_date)',
            'op', 'AGGREGATION'
        ),
        named_struct(
            'name', 'tier',
            'expression', 'loyalty_tier(total_revenue)',
            'op', 'UDF'
        )
    )
    ) AS _lineage
FROM `dev_fd_silver`.`ben_sales`.`customer_orders`
GROUP BY
    customer_id, first_name, last_name, email, country
;

-- Execution summary
SELECT
    'customer_summary' AS model,
    'table' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_silver`.`ben_sales`.`customer_summary`) AS rows_created,
    current_timestamp() AS completed_at;

-- Lineage log (run_id captured at runtime)
INSERT INTO `dev_fd_meta`.`ben_sales`.lineage_log
    (run_id, model, materialized, rows_created, catalog, schema, sources, git_commit, completed_at)
SELECT
    '{{job.run_id}}',
    'customer_summary',
    'table',
    COUNT(*),
    'dev_fd_silver',
    'ben_sales',
    'customer_orders',
    'unknown',
    current_timestamp()
FROM `dev_fd_silver`.`ben_sales`.`customer_summary`;
