-- Model: stg_orders
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE SCHEMA IF NOT EXISTS `dev_fd_silver`.`ben_sales`;

CREATE OR REPLACE VIEW `dev_fd_silver`.`ben_sales`.`stg_orders` AS
SELECT
    order_id,
    customer_id,
    product,
    quantity,
    cast(unit_price as decimal(10,2)) as unit_price,
    quantity * unit_price as line_total,
    cast(order_date as date) as order_date,
    named_struct(
        'schema_version', '4',
        'model', 'stg_orders',
        'sources', 'raw_orders',
        'origin_files', coalesce(_lineage.origin_files, array(_origin_file)),
        'ingested_ats', coalesce(_lineage.ingested_ats, array(_inserted_at)),
        'upstream', to_json(_lineage),
        'git_commit', 'unknown',
        'deployed_at', '2026-03-24T22:49:10.324394+00:00',
        'compute_type', 'serverless',
        'contract_id', 'ben_sales.stg_orders',
        'version', 'v1',
        'columns', array(
        named_struct(
            'name', 'order_id',
            'expression', 'order_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'product',
            'expression', 'product',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'quantity',
            'expression', 'quantity',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'unit_price',
            'expression', 'cast(unit_price as decimal(10,2))',
            'op', 'CAST'
        ),
        named_struct(
            'name', 'line_total',
            'expression', 'quantity * unit_price',
            'op', 'EXPRESSION'
        ),
        named_struct(
            'name', 'order_date',
            'expression', 'cast(order_date as date)',
            'op', 'CAST'
        )
    )
    ) AS _lineage
FROM `dev_fd_bronze`.`ben_sales`.`raw_orders`
;

-- Execution summary
SELECT
    'stg_orders' AS model,
    'view' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_silver`.`ben_sales`.`stg_orders`) AS rows_created,
    current_timestamp() AS completed_at;

-- Lineage log (run_id captured at runtime)
INSERT INTO `dev_fd_meta`.`ben_lineage`.lineage_log
    (run_id, model, materialized, rows_created, catalog, schema, sources, git_commit, completed_at)
SELECT
    :run_id,
    'stg_orders',
    'view',
    COUNT(*),
    'dev_fd_silver',
    'ben_sales',
    'raw_orders',
    'unknown',
    current_timestamp()
FROM `dev_fd_silver`.`ben_sales`.`stg_orders`;
