-- Model: customer_orders
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE SCHEMA IF NOT EXISTS `dev_fd_silver`.`ben_sales`;

CREATE TABLE IF NOT EXISTS `dev_fd_silver`.`ben_sales`.`customer_orders` (
    customer_id STRING,
    first_name STRING,
    last_name STRING,
    email STRING,
    country STRING,
    order_id STRING NOT NULL,
    product STRING,
    quantity STRING,
    unit_price STRING,
    line_total STRING,
    order_date STRING,
    _lineage STRUCT<schema_version: STRING, model: STRING, sources: STRING, origin_files: ARRAY<STRING>, ingested_ats: ARRAY<TIMESTAMP>, upstream: STRING, git_commit: STRING, deployed_at: STRING, compute_type: STRING, contract_id: STRING, version: STRING, columns: ARRAY<STRUCT<name: STRING, expression: STRING, op: STRING>>>
) USING DELTA;

TRUNCATE TABLE `dev_fd_silver`.`ben_sales`.`customer_orders`;

INSERT INTO `dev_fd_silver`.`ben_sales`.`customer_orders`
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.email,
    c.country,
    o.order_id,
    o.product,
    o.quantity,
    o.unit_price,
    o.line_total,
    o.order_date,
    named_struct(
        'schema_version', '4',
        'model', 'customer_orders',
        'sources', 'customer_clean, stg_orders',
        'origin_files', array_union(coalesce(c._lineage.origin_files, array(c._origin_file)), coalesce(o._lineage.origin_files, array(o._origin_file))),
        'ingested_ats', array_union(coalesce(c._lineage.ingested_ats, array(c._inserted_at)), coalesce(o._lineage.ingested_ats, array(o._inserted_at))),
        'upstream', concat('[', coalesce(to_json(c._lineage), 'null'), ',', coalesce(to_json(o._lineage), 'null'), ']'),
        'git_commit', 'unknown',
        'deployed_at', '2026-03-24T22:49:10.324394+00:00',
        'compute_type', 'serverless',
        'contract_id', 'ben_sales.customer_orders',
        'version', 'v1',
        'columns', array(
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'first_name',
            'expression', 'first_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'last_name',
            'expression', 'last_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'email',
            'expression', 'email',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'country',
            'expression', 'country',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'order_id',
            'expression', 'order_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'product',
            'expression', 'product',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'quantity',
            'expression', 'quantity',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'unit_price',
            'expression', 'unit_price',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'line_total',
            'expression', 'line_total',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'order_date',
            'expression', 'order_date',
            'op', 'PASSTHROUGH'
        )
    )
    ) AS _lineage
FROM `dev_fd_silver`.`ben_sales`.`customer_clean` c
INNER JOIN `dev_fd_silver`.`ben_sales`.`stg_orders` o
    ON c.customer_id = o.customer_id
;

-- Execution summary
SELECT
    'customer_orders' AS model,
    'table' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_silver`.`ben_sales`.`customer_orders`) AS rows_created,
    current_timestamp() AS completed_at;

-- Lineage log (run_id captured at runtime)
INSERT INTO `dev_fd_meta`.`ben_lineage`.lineage_log
    (run_id, model, materialized, rows_created, catalog, schema, sources, git_commit, completed_at)
SELECT
    :run_id,
    'customer_orders',
    'table',
    COUNT(*),
    'dev_fd_silver',
    'ben_sales',
    'customer_clean,stg_orders',
    'unknown',
    current_timestamp()
FROM `dev_fd_silver`.`ben_sales`.`customer_orders`;
