-- Model: customer_summary
-- Generated by: forge compile --pure-sql
-- No dbt required. Runs directly on SQL warehouse.

CREATE SCHEMA IF NOT EXISTS `dev_fd_silver`.`ben_sales`;

CREATE TABLE IF NOT EXISTS `dev_fd_silver`.`ben_sales`.`customer_summary` (
    customer_id INT NOT NULL,
    first_name STRING,
    last_name STRING,
    email STRING,
    country STRING,
    total_orders INT,
    total_revenue DECIMAL(10,2),
    first_order_date DATE,
    last_order_date DATE,
    tier STRING,
    _lineage STRUCT<schema_version: STRING, model: STRING, sources: STRING, origin_files: ARRAY<STRING>, ingested_ats: ARRAY<TIMESTAMP>, upstream: STRING, git_commit: STRING, deployed_at: STRING, compute_type: STRING, contract_id: STRING, version: STRING, columns: ARRAY<STRUCT<name: STRING, expression: STRING, op: STRING>>>
) USING DELTA;

TRUNCATE TABLE `dev_fd_silver`.`ben_sales`.`customer_summary`;

INSERT INTO `dev_fd_silver`.`ben_sales`.`customer_summary`
WITH _agg AS (
    SELECT
        customer_id,
        first_name,
        last_name,
        email,
        country,
        count(order_id) as total_orders,
        sum(line_total) as total_revenue,
        min(order_date) as first_order_date,
        max(order_date) as last_order_date,
        array_distinct(flatten(collect_list(coalesce(_lineage.origin_files, array(_origin_file))))) as _collected_origin_files,
        array_distinct(flatten(collect_list(coalesce(_lineage.ingested_ats, array(_inserted_at))))) as _collected_ingested_ats
    FROM `dev_fd_silver`.`ben_sales`.`customer_orders`
    GROUP BY
        customer_id, first_name, last_name, email, country
)
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    country,
    total_orders,
    total_revenue,
    first_order_date,
    last_order_date,
    `dev_fd_silver`.`ben_sales`.loyalty_tier(total_revenue) as tier,
    named_struct(
        'schema_version', '4',
        'model', 'customer_summary',
        'sources', 'customer_orders',
        'origin_files', _collected_origin_files,
        'ingested_ats', _collected_ingested_ats,
        'upstream', cast(null as string),
        'git_commit', 'unknown',
        'deployed_at', '2026-03-24T22:49:10.324394+00:00',
        'compute_type', 'serverless',
        'contract_id', 'ben_sales.customer_summary',
        'version', 'v1',
        'columns', array(
        named_struct(
            'name', 'customer_id',
            'expression', 'customer_id',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'first_name',
            'expression', 'first_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'last_name',
            'expression', 'last_name',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'email',
            'expression', 'email',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'country',
            'expression', 'country',
            'op', 'PASSTHROUGH'
        ),
        named_struct(
            'name', 'total_orders',
            'expression', 'count(order_id)',
            'op', 'AGGREGATION'
        ),
        named_struct(
            'name', 'total_revenue',
            'expression', 'sum(line_total)',
            'op', 'AGGREGATION'
        ),
        named_struct(
            'name', 'first_order_date',
            'expression', 'min(order_date)',
            'op', 'AGGREGATION'
        ),
        named_struct(
            'name', 'last_order_date',
            'expression', 'max(order_date)',
            'op', 'AGGREGATION'
        ),
        named_struct(
            'name', 'tier',
            'expression', 'loyalty_tier(total_revenue)',
            'op', 'UDF'
        )
    )
    ) AS _lineage
FROM _agg
;

-- Execution summary
SELECT
    'customer_summary' AS model,
    'table' AS materialized,
    (SELECT COUNT(*) FROM `dev_fd_silver`.`ben_sales`.`customer_summary`) AS rows_created,
    current_timestamp() AS completed_at;

-- Lineage log (run_id captured at runtime)
INSERT INTO `dev_fd_meta`.`ben_lineage`.lineage_log
    (run_id, model, materialized, rows_created, catalog, schema, sources, git_commit, completed_at)
SELECT
    :run_id,
    'customer_summary',
    'table',
    COUNT(*),
    'dev_fd_silver',
    'ben_sales',
    'customer_orders',
    'unknown',
    current_timestamp()
FROM `dev_fd_silver`.`ben_sales`.`customer_summary`;
