-- ============================================
-- BACKUP: Archive all table data before teardown
-- Generated by: forge compile --pure-sql
-- ============================================

CREATE SCHEMA IF NOT EXISTS `dev_fd_ops`.`ben_backups`;

CREATE TABLE IF NOT EXISTS `dev_fd_ops`.`ben_backups`.`_backup_archive` (
  asset_name STRING,
  asset_type STRING,
  project STRING,
  environment STRING,
  archived_at TIMESTAMP,
  performed_by STRING,
  git_sha STRING,
  git_branch STRING,
  dab_name STRING,
  row_count BIGINT,
  snapshot_data STRING
) USING DELTA;

INSERT INTO `dev_fd_ops`.`ben_backups`.`_backup_archive` SELECT 'file_manifest' AS asset_name, 'table' AS asset_type, 'sales_data' AS project, 'dev' AS environment, current_timestamp() AS archived_at, current_user() AS performed_by, '089277b' AS git_sha, 'test/sales-project' AS git_branch, 'PROCESS_sales' AS dab_name, COUNT(*) AS row_count, to_json(collect_list(to_json(struct(*)))) AS snapshot_data FROM `dev_fd_bronze`.`ben_sales`.`file_manifest`;
INSERT INTO `dev_fd_ops`.`ben_backups`.`_backup_archive` SELECT 'raw_customers' AS asset_name, 'table' AS asset_type, 'sales_data' AS project, 'dev' AS environment, current_timestamp() AS archived_at, current_user() AS performed_by, '089277b' AS git_sha, 'test/sales-project' AS git_branch, 'PROCESS_sales' AS dab_name, COUNT(*) AS row_count, to_json(collect_list(to_json(struct(*)))) AS snapshot_data FROM `dev_fd_bronze`.`ben_sales`.`raw_customers`;
INSERT INTO `dev_fd_ops`.`ben_backups`.`_backup_archive` SELECT 'raw_orders' AS asset_name, 'table' AS asset_type, 'sales_data' AS project, 'dev' AS environment, current_timestamp() AS archived_at, current_user() AS performed_by, '089277b' AS git_sha, 'test/sales-project' AS git_branch, 'PROCESS_sales' AS dab_name, COUNT(*) AS row_count, to_json(collect_list(to_json(struct(*)))) AS snapshot_data FROM `dev_fd_bronze`.`ben_sales`.`raw_orders`;
INSERT INTO `dev_fd_ops`.`ben_backups`.`_backup_archive` SELECT 'customer_clean' AS asset_name, 'table' AS asset_type, 'sales_data' AS project, 'dev' AS environment, current_timestamp() AS archived_at, current_user() AS performed_by, '089277b' AS git_sha, 'test/sales-project' AS git_branch, 'PROCESS_sales' AS dab_name, COUNT(*) AS row_count, to_json(collect_list(to_json(struct(*)))) AS snapshot_data FROM `dev_fd_silver`.`ben_sales`.`customer_clean`;
INSERT INTO `dev_fd_ops`.`ben_backups`.`_backup_archive` SELECT 'customer_clean_quarantine' AS asset_name, 'table' AS asset_type, 'sales_data' AS project, 'dev' AS environment, current_timestamp() AS archived_at, current_user() AS performed_by, '089277b' AS git_sha, 'test/sales-project' AS git_branch, 'PROCESS_sales' AS dab_name, COUNT(*) AS row_count, to_json(collect_list(to_json(struct(*)))) AS snapshot_data FROM `dev_fd_silver`.`ben_sales`.`customer_clean_quarantine`;
INSERT INTO `dev_fd_ops`.`ben_backups`.`_backup_archive` SELECT 'customer_orders' AS asset_name, 'table' AS asset_type, 'sales_data' AS project, 'dev' AS environment, current_timestamp() AS archived_at, current_user() AS performed_by, '089277b' AS git_sha, 'test/sales-project' AS git_branch, 'PROCESS_sales' AS dab_name, COUNT(*) AS row_count, to_json(collect_list(to_json(struct(*)))) AS snapshot_data FROM `dev_fd_silver`.`ben_sales`.`customer_orders`;
INSERT INTO `dev_fd_ops`.`ben_backups`.`_backup_archive` SELECT 'customer_summary' AS asset_name, 'table' AS asset_type, 'sales_data' AS project, 'dev' AS environment, current_timestamp() AS archived_at, current_user() AS performed_by, '089277b' AS git_sha, 'test/sales-project' AS git_branch, 'PROCESS_sales' AS dab_name, COUNT(*) AS row_count, to_json(collect_list(to_json(struct(*)))) AS snapshot_data FROM `dev_fd_silver`.`ben_sales`.`customer_summary`;

INSERT INTO `dev_fd_ops`.`ben_backups`.`_backup_archive` SELECT 'lineage_graph' AS asset_name, 'table' AS asset_type, 'sales_data' AS project, 'dev' AS environment, current_timestamp() AS archived_at, current_user() AS performed_by, '089277b' AS git_sha, 'test/sales-project' AS git_branch, 'PROCESS_sales' AS dab_name, COUNT(*) AS row_count, to_json(collect_list(to_json(struct(*)))) AS snapshot_data FROM `dev_fd_meta`.`ben_lineage`.`lineage_graph`;
INSERT INTO `dev_fd_ops`.`ben_backups`.`_backup_archive` SELECT 'lineage_log' AS asset_name, 'table' AS asset_type, 'sales_data' AS project, 'dev' AS environment, current_timestamp() AS archived_at, current_user() AS performed_by, '089277b' AS git_sha, 'test/sales-project' AS git_branch, 'PROCESS_sales' AS dab_name, COUNT(*) AS row_count, to_json(collect_list(to_json(struct(*)))) AS snapshot_data FROM `dev_fd_meta`.`ben_lineage`.`lineage_log`;

