-- ============================================
-- TEARDOWN: Drop all forge-managed objects
-- Generated by: forge compile --pure-sql
-- Mode: schema_cascade
-- ============================================

DROP FUNCTION IF EXISTS `dev_fd_silver`.`ben_sales`.average_score;
DROP FUNCTION IF EXISTS `dev_fd_silver`.`ben_sales`.clean_email;
DROP FUNCTION IF EXISTS `dev_fd_silver`.`ben_sales`.loyalty_tier;
DROP FUNCTION IF EXISTS `dev_fd_meta`.`ben_lineage`.trace_lineage;
DROP FUNCTION IF EXISTS `dev_fd_meta`.`ben_lineage`.trace_lineage_json;
DROP FUNCTION IF EXISTS `dev_fd_meta`.`ben_lineage`.last_run_id;

DROP SCHEMA IF EXISTS `dev_fd_bronze`.`ben_sales` CASCADE;
DROP SCHEMA IF EXISTS `dev_fd_meta`.`ben_lineage` CASCADE;
DROP SCHEMA IF EXISTS `dev_fd_silver`.`ben_sales` CASCADE;

